# .github/workflows/deploy.yml
name: Deploy Lambda to AWS

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd cdk && npm ci
      - name: Determine environment and account
        id: env
        run: |
          set -x  # Habilita el modo debug para ver cada comando ejecutado

          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "env_name=prod" >> $GITHUB_OUTPUT
            echo "account_id=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_OUTPUT
          else
            echo "env_name=dev" >> $GITHUB_OUTPUT
            echo "account_id=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_OUTPUT
          fi

          echo "Assigned env_name: ${{ steps.env.outputs.env_name }}"
          echo "Assigned account_id: ${{ steps.env.outputs.account_id }}"


      - name: Debug environment values
        run: |
          echo "env_name: ${{ steps.env.outputs.env_name }}"
          echo "account_id: ${{ steps.env.outputs.account_id }}"

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ steps.env.outputs.account_id }}:role/GithubActionsRole
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
          role-session-name: GithubActionsSession

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy with CDK
        env:
          AWS_ACCOUNT_ID: ${{ steps.env.outputs.account_id }}
          AWS_ACCOUNT_ID_DEV: ${{ secrets.AWS_ACCOUNT_ID_DEV }}
          AWS_ACCOUNT_ID_PROD: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
          AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
        run: |
          cd cdk
          npm run cdk deploy -- --context env=${{ steps.env.outputs.env_name }} --context accountId=${{ steps.env.outputs.account_id }} --require-approval never

      - name: Update Lambda Alias
        if: ${{ steps.env.outputs.env_name == 'prod' }}
        run: |
          VERSION=$(aws lambda publish-version \
            --function-name aws-deploy-test-prod \
            --description "Deployed from GitHub Actions" \
            --query 'Version' --output text)
          
          aws lambda update-alias \
            --function-name aws-deploy-test-prod \
            --name prod \
            --function-version $VERSION